### ISSUE TITLE
review on indexer for polkadot xcm review

### ISSUE THREAD

**Issue by happyJ2024** [web3go-xyz/indexer-polkadot-xcm#1]
xcm doc: 
https://www.notion.so/web3go/XCM-Relay-chain-related-event-extrinsic-bdb19655ff094b0781ec0294c629548c

**Comment by happyJ2024** [comment]
![Image](https://user-images.githubusercontent.com/12878885/192304081-f452b1a5-e6dd-4c6d-9e67-fc3a1ffd30da.png)



![Image](https://user-images.githubusercontent.com/12878885/192304109-52581c24-d46e-4d26-af40-64c8f56f1306.png)

**Comment by happyJ2024** [comment]
- [x] code finished
- [x] code reviewed
- [x] running , estimation

**Comment by zhanggoodzhi** [comment]
estimate min time is 4 days, max is 12 days.

**Comment by happyJ2024** [comment]
code reviewed.
the data is OK.

**Comment by happyJ2024** [comment]
![Image](https://user-images.githubusercontent.com/12878885/194984576-d002264d-48a8-48ea-a302-316fd77fc289.png)
